// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.176
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaskRunnerExtension
{
    static class Vsix
    {
        public const string Id = "3f0e7a25-a178-46c6-b123-11006018f774";
        public const string Name = "TaskRunnerExtension";
        public const string Description = "Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
