// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.176
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaskRunnerTemplate
{
    static class Vsix
    {
        public const string Id = "e3f7a0d3-f521-4da8-8fa3-e3a07702328a";
        public const string Name = "Task Runner Project Template";
        public const string Description = "A project template for building Task Runner Explorer extensions for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "Task Runner Explorer, extension, VSIX";
    }
}
